- hosts: terraform-ansible
  tasks:
    - name: instalando-python3-virtualenv
      apt:
        pkg:
          -  python3
          - virtualenv
        update_cache: yes
      become: yes
    - name: instalando-dependencia-com-pip-django-django-rest
      pip:
        virtualenv: /home/ubuntu/tcc/venv
        name:
          - django
          - djangorestframework
    - name: verifica-se-projeto-existe
      stat:
        path: /home/ubuntu/tcc/setup/settings.py
      register: projeto
    - name: iniciando-projeto
      shell: '. /home/ubuntu/tcc/venv/bin/activate; django-admin startproject setup /home/ubuntu/tcc/'
      when: not projeto.stat.exists
    - name: alterando-host-settings-django
      lineinfile:
        path: /home/ubuntu/tcc/setup/settings.py
        regexp: 'ALLOWED_HOSTS'
        line: 'ALLOWED_HOSTS = ["*"]'
        backrefs: yes